### PR TITLE
Fix string encoding issue

### LINKED ISSUE #619: Serialize or/and Deserialize failing
Hello guys :wink: ,

Well my main project is now failling its Apis calls that contains objects to post.

### Before Update 

image

1 - From the web browser

image

2 - From the web browser

### After Update

image

3 -From the web browser

image

4 - From the web browser

image

5 - From the terminal

Here is my code 

#### Send email to backend for checking

```rust
      let email_form = FormEmail::new(model.email.clone());

            let request = Request::new("/api/email")
                .method(Method::Post)
                .json(&email_form)
                .expect("Serialization failed");
                
                
         orders.perform_cmd(async {
                RequestState::send(request)
                    .await
                    .map_err(|e| e.message().to_string())
                    .map_or_else(Msg::ValidateEmailFailed, Msg::ValidateEmailSucceed)
            });          

```

#### RequestState is a wrapper for making request and getting error message from backend 

```rust 
impl<T: 'static + DeserializeOwned> RequestState<T> {
    /// Send the request with `fetch(request).await?;` and catch every possible
    /// `FetchError` to ClientError;
    #[allow(clippy::needless_lifetimes)]
    pub async fn send<'a>(request: Request<'a>) -> Result<T, ClientError> {
        let response = fetch(request).await?;
        let status = response.status();

        if status.is_error() {
            let text = response.text().await?;
            return Err(ClientError::new(&text, &status.code.to_string()));
        }
        Ok(response.json().await?)
    }

    pub fn is_loading(&self) -> bool {
        match self {
            RequestState::IsPending(is_loading) => *is_loading,
            _ => false,
        }
    }
}
```

#### The data Model 

```rust

use serde::{Deserialize, Serialize};
#[derive(Deserialize, Serialize)]
pub struct FormEmail {
    email: String,
}
```

I do not know what is happening there and why my object is not passed like before as json. 

Any clue or indication on what I could do to fix it ?

### PR DESCRIPTION
**Pull request by fosskers**
~~I would love it if there were a better way to canonically turn a `JsValue` into a `String`.~~ There is!

Closes #619

### CODE REVIEW

File: src/browser/web_socket.rs [hunk 1]
```diff
@@ -131,7 +132,8 @@ impl WebSocket {
     ///
     /// Returns error when JSON serialization or sending fails.
     pub fn send_json<T: Serialize + ?Sized>(&self, data: &T) -> Result<()> {
-        let data = swb::to_value(data)?
+        let data = JSON::stringify(&swb::to_value(data)?)
+            .map_err(|_| WebSocketError::ConversionError)?
             .as_string()
             .ok_or(WebSocketError::ConversionError)?;
```
Comment (RReverser) [inline src/browser/web_socket.rs:138]: Since `JSON::stringify` returns a `JsString`, you can instead use infallible `String::from(...)` on it (or `.into()` equivalent).

Comment (fosskers) [reply src/browser/web_socket.rs:138]: That's way better, thank you. I must have somehow missed that those trait instances existed.

Comment (fosskers) [reply src/browser/web_socket.rs:138]:
```rust
impl<'a> From<&'a JsString> for String {
    fn from(s: &'a JsString) -> Self {
        s.obj.as_string().unwrap_throw()
    }
}
```
I thought `From` was never supposed to panic.

Comment (RReverser) [reply src/browser/web_socket.rs:138]: It won't because type is statically known here.

Comment (RReverser) [reply src/browser/web_socket.rs:138]: Also, `.unwrap_throw()` doesn't panic in Rust terms, it's much more lightweight method as it immediately throws JS exception that unwinds entire JS stack.
